In [2]:
import numpy as np

In [18]:
class student:
    def __init__(self, name):
        self._name = name
    def name(self):
        return self._name

In [21]:
s = student("yousef")
s.name()

'yousef'

In [23]:
s = np.array(5)
print(s.ndim)
print(s.shape)

print("----------------")

v = np.array([1,2,3,4])
print(v.ndim)
print(v.shape)

print("----------------")

m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m.ndim)
print(m.shape)




0
()
----------------
1
(4,)
----------------
2
(3, 3)


In [28]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape(3,2)
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [30]:
vec = np.array([1,2,3,4])
mat = vec.reshape(vec.shape[0],1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [45]:
def array_reshape(arr, rows, cols):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape opration: {e}")
    

    

In [48]:
vec = [1,2,3,4,5,6]

array_reshape(vec, 2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
# object --> string --> float --> int --> pool
mat = np.array([[1,2,3],
                [4,5.5,6],
                [7,8,9]])
fmat = mat.astype(str)
print(fmat.dtype)

<U32


In [ ]:
def convert_dtype(arr, dtype):
    if not isinstance(arr,np.ndarray):

    arr = np.array(arr)
    return arr.astype(dtype)


In [56]:
v = np.array([3,2,5,1])
v[3]

np.int64(1)

In [74]:
m = np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [0,0,0]])

m[-3:-1, -3:-1]


array([[4, 5],
       [7, 8]])

In [63]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mat.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
mat = np.full((3,4),5)
mat

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [75]:
mat = np.empty((3,3))
mat

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ],
       [7. , 8. , 9. ]])

In [76]:
angles = np.arange(0,361,90)
angles

array([  0,  90, 180, 270, 360])

In [79]:
vec = np.linspace(0, 10 , num = 25)
mar = vec.reshape(5,5)
mat

array([[1. , 2. , 3. ],
       [4. , 5.5, 6. ],
       [7. , 8. , 9. ]])

In [80]:
i = np.identity(3, dtype="float32")
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
np.random.random((3,3))

array([2, 0], dtype=int32)

In [85]:
np.random.randint(0, 11,(5,5))

array([[ 8,  1,  2, 10,  3],
       [ 8,  7,  0,  4,  5],
       [ 7,  6,  3,  3,  8],
       [ 0,  1,  6,  3,  3],
       [ 7,  8,  2,  5,  5]], dtype=int32)

In [87]:
a = ["yousef", "rahma", "aya"]
np.random.choice(a, size=(3,5))

array([['yousef', 'aya', 'rahma', 'rahma', 'aya'],
       ['yousef', 'rahma', 'aya', 'aya', 'yousef'],
       ['rahma', 'rahma', 'yousef', 'rahma', 'rahma']], dtype='<U6')

In [89]:
mat1 = np.ones((3,4))
mat2 = np.zeros((5,3))
# np.savez('new_np.npz', ones_mar = mat1, zeros_mat = mat2)

In [93]:
with np.load('new_np.npz') as file:
    mat1 = file['ones_mar']
    mat2 = file['zeros_mat']

In [94]:
mat1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
m1 = np.array([[1,2,3],
               [0,0,0]])

m2 = np.array([[4,5,6],
               [1,1,1]])

mat1 = np.vstack((m1,m2))

mat2 = np.hstack((m1,m2))
print(mat1)
print("--------------")
print(mat2)

[[1 2 3]
 [0 0 0]
 [4 5 6]
 [1 1 1]]
--------------
[[1 2 3 4 5 6]
 [0 0 0 1 1 1]]


In [104]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.isclose(v1, v2, atol=3)


array([ True,  True,  True])

In [106]:
v = np.array([2,4,3,4,10])
condition = v >=4
v[condition] = -1
print(v)

[ 2 -1  3 -1 -1]
